{% set version = "1.27.3" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-hexbin
  version: {{ version|replace("-", "_") }}

source:
  fn: hexbin_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/hexbin_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/hexbin/hexbin_{{ version }}.tar.gz
  sha256: 7ea422a76542c2fc2840df601af1b7803aa96df4fee6d51dec456ac36940c191

build:
  merge_build_host: True  # [win]
  number: 0
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('fortran') }}  # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-lattice
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-lattice

test:
  commands:
    - $R -e "library('hexbin')"           # [not win]
    - "\"%R%\" -e \"library('hexbin')\""  # [win]

about:
  home: http://github.com/edzer/hexbin
  license: GPL-2
  summary: Binning and plotting functions for hexagonal bins.
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
