{% set version = "1.27.2" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-hexbin
  version: {{ version|replace("-", "_") }}

source:
  fn: hexbin_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/hexbin_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/hexbin/hexbin_{{ version }}.tar.gz
  sha256: 46d47b1efef75d6f126af686a4dd614228b60418b9a5bde9e9e5d11200a0ee52

build:
  number: 0
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-lattice
    - posix                # [win]
    - {{native}}toolchain  # [win]
    - gcc                  # [not win]

  run:
    - r-base
    - r-lattice

test:
  commands:
    - $R -e "library('hexbin')"  # [not win]
    - "\"%R%\" -e \"library('hexbin')\""  # [win]

about:
  home: http://github.com/edzer/hexbin
  license: GPL-2
  summary: Binning and plotting functions for hexagonal bins. Now uses and relies on grid graphics
    and formal (S4) classes and methods.
  license_family: GPL2

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
