appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: tZYUs29JWNXruSCiDjF1Be7gzfNKZxCTIlqDN1ZOvLObXedqVEC7nu0d6mZkgQcatCyRRUoe034ey9KCdweV1mqfQUTbbD26Wpgwc6EKOprDyvkBYTFnF2sTefH49rMDFzDWHqoDk9Rp25CANf6ExxuRsVgYkP4E/pc6aI84EZ66yUIa0CFTIVlYtn/3CYO4VTsll0hkAmo8z2XEagevI+V3UHX5OnFDsjsvs58qc7ODBGZEBN23A3r8QoCrI9zfNFTBilgFH7qUv7ayo6adurdf1tRJiWYrhyUKega7z/M33ixJm5WTuUf7qHjCELTB01OU2BgNVoG6Qn6IaNLQzdO0umhIhPTT0ZM33mDn9+bm/tzy91z/2+Z8elgMqkMNDWb2Wfjs4RM3B+ZQjJPyZgGwn4DFfaCxM5LeAlPaRYYt1UIims+MKuBY7ruvgLXOjxDjr6EzqbPj9jhT9P90Urzdbo/gjw7QTi+YS/SUVv60rvhIAaZrv8aDHZ6BL4UOLxT6QipdHjpLVx6dVp4anhkKgP6Dfp9XMmjJt/oTRuCtGslTko/gDMG46xXai5dyLVIHUxzGoxSuT6j7yHRPDdISUhI0ggzZSwR9rM4G+TX32X44OkVSSMSnjPonQqxKpr974vd/D1fn8hDC4/GjAHvfSMdlYyFBQq7p+0anntI=}
